name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: x64
            cmake_tuple: x64-x64
            openssl_tuple: x64-amd64-VC-WIN64A
            ffmpeg_tuple: x64-amd64
            libplacebo_tuple: x64-CLANG64
          - os: windows-latest
            platform: ARM64
            cmake_tuple: ARM64-ARM64
            openssl_tuple: arm64-amd64_arm64-VC-WIN64-ARM
            ffmpeg_tuple: arm64-amd64_arm64
            libplacebo_tuple: ARM64-CLANGARM64
          - os: windows-latest
            platform: x86
            cmake_tuple: x86-x86
            openssl_tuple: x86-x86-VC-WIN32
            ffmpeg_tuple: x86-x86
            libplacebo_tuple: x86-CLANG32
          - os: macos-11.0
            platform: macOS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize Submodules
        run: git submodule update --init

      - name: Install NASM
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            choco install nasm -y
          elif [ "${{ runner.os }}" == "macOS" ]; then
            brew install nasm
          fi
        shell: bash

      - name: Install Vulkan SDK
        if: ${{ runner.os == 'Windows' }}
        run: |
          curl -o vulkan_sdk.exe https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe
          ./vulkan_sdk.exe --root C:\Vulkan --accept-licenses --default-answer --confirm-command install
        shell: pwsh

      - name: Build and Test
        run: |
          mkdir build
          cd build
          mkdir SDL
          cd SDL
          ..\..\build-sdl.bat ${{ matrix.cmake_tuple }}
          cd ..
        if: runner.os == 'Windows'
        shell: cmd
      
      - name: Build and Test (non-Windows)
        run: |
          mkdir build
          cd build
          mkdir SDL
          cd SDL
          ../../build-sdl.sh
          cd ..
        if: runner.os != 'Windows'
        shell: bash

      - name: Build SDL_ttf (Windows)
        if: matrix.os == 'windows-latest'
        run: |
            mkdir SDL_ttf
            cd SDL_ttf
            ..\build-sdl-ttf.bat ${{ matrix.cmake_tuple }}
            cd ..
        shell: cmd

      - name: Build OpenSSL
        run: |
            mkdir openssl
            cd openssl
            ..\build-openssl.bat ${{ matrix.openssl_tuple }}
            cd ..
        if: matrix.os == 'windows-latest'
        shell: cmd

      - name: Build OpenSSL (macOS and Linux)
        run: |
            mkdir openssl
            cd openssl
            ../build-openssl.sh x64 darwin64-x86_64-cc
            ../build-openssl.sh arm64 darwin64-arm64-cc
            cd ..
        if: matrix.os != 'windows-latest'
        shell: bash

      - name: Build and setup libplacebo (Windows)
        if: matrix.os == 'windows-latest'
        run: |
            mkdir libplacebo
            cd libplacebo
            cmd /c ..\build-libplacebo-windows.bat ${{ matrix.libplacebo_tuple }}
            cd ..
        shell: cmd
      
      - name: Build dav1d
        run: |
            mkdir dav1d
            cd dav1d
            ..\build-dav1d.bat ${{ matrix.ffmpeg_tuple }}
            cd ..
        if: matrix.os == 'windows-latest'
        shell: cmd

      - name: Build dav1d (non-Windows)
        run: |
            mkdir dav1d
            cd dav1d
            ../../build-dav1d.sh
            cd ..
        if: matrix.os != 'windows-latest'
        shell: bash

      - name: Build FFmpeg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
            mkdir FFmpeg
            cd FFmpeg
            cmd /c ..\build-ffmpeg-windows.bat ${{ matrix.ffmpeg_tuple }}
            cd ..
        shell: cmd

      - name: Build FFmpeg (macOS)
        if: matrix.os == 'macos-latest'
        run: |
            mkdir FFmpeg
            cd FFmpeg
            ../build-ffmpeg-macos.sh x64 x86_64
            ../build-ffmpeg-macos.sh arm64 arm64
            cd ..
        shell: bash

      - name: Build Opus (Windows)
        if: matrix.os == 'windows-latest'
        run: |
            mkdir opus
            cd opus
            ..\..\build-opus.bat ${{ matrix.cmake_tuple }}
            cd ..
        shell: cmd

      - name: Build Opus (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
            mkdir opus
            cd opus
            ../../build-opus.sh x64 x86_64
            ../../build-opus.sh arm64 arm64
            cd ..
        shell: bash

      - name: Build discord-rpc (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir discord-rpc
          cd discord-rpc
          ..\..\build-discord-rpc.bat ${{ matrix.cmake_tuple }}
          cd ..
        shell: cmd
  
      - name: Build discord-rpc (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir discord-rpc
          cd discord-rpc
          ../../build-discord-rpc.sh x64 x86_64
          ../../build-discord-rpc.sh arm64 arm64
          cd ..
        shell: bash

      - name: Archive Artifacts
        if: ${{ runner.os == 'Windows' }}
        run: cmd /c archive.bat ${{ matrix.platform }}
        shell: cmd

      - name: Upload Artifact (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: windows-${{ matrix.platform }}.zip
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false
